//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomizeDesigners.Dbml
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Database
    {
        
        private Connection connectionField;
        
        private System.Collections.Generic.List<Table> tableField;
        
        private System.Collections.Generic.List<Function> functionField;
        
        private string nameField;
        
        private string entityNamespaceField;
        
        private string contextNamespaceField;
        
        private string classField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private ClassModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        private string baseTypeField;
        
        private string providerField;
        
        private bool externalMappingField;
        
        private bool externalMappingFieldSpecified;
        
        private SerializationMode serializationField;
        
        private bool serializationFieldSpecified;
        
        private string entityBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Connection Connection
        {
            get
            {
                return this.connectionField;
            }
            set
            {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Table", Order=1)]
        public System.Collections.Generic.List<Table> Table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Function", Order=2)]
        public System.Collections.Generic.List<Function> Function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntityNamespace
        {
            get
            {
                return this.entityNamespaceField;
            }
            set
            {
                this.entityNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContextNamespace
        {
            get
            {
                return this.contextNamespaceField;
            }
            set
            {
                this.contextNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ClassModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ExternalMapping
        {
            get
            {
                return this.externalMappingField;
            }
            set
            {
                this.externalMappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExternalMappingSpecified
        {
            get
            {
                return this.externalMappingFieldSpecified;
            }
            set
            {
                this.externalMappingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SerializationMode Serialization
        {
            get
            {
                return this.serializationField;
            }
            set
            {
                this.serializationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerializationSpecified
        {
            get
            {
                return this.serializationFieldSpecified;
            }
            set
            {
                this.serializationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntityBase
        {
            get
            {
                return this.entityBaseField;
            }
            set
            {
                this.entityBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Connection
    {
        
        private string providerField;
        
        private ConnectionMode modeField;
        
        private bool modeFieldSpecified;
        
        private string connectionStringField;
        
        private string settingsObjectNameField;
        
        private string settingsPropertyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConnectionMode Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModeSpecified
        {
            get
            {
                return this.modeFieldSpecified;
            }
            set
            {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectionString
        {
            get
            {
                return this.connectionStringField;
            }
            set
            {
                this.connectionStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SettingsObjectName
        {
            get
            {
                return this.settingsObjectNameField;
            }
            set
            {
                this.settingsObjectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SettingsPropertyName
        {
            get
            {
                return this.settingsPropertyNameField;
            }
            set
            {
                this.settingsPropertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum ConnectionMode
    {
        
        /// <remarks/>
        ConnectionString,
        
        /// <remarks/>
        AppSettings,
        
        /// <remarks/>
        WebSettings,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Return
    {
        
        private string typeField;
        
        private string dbTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DbType
        {
            get
            {
                return this.dbTypeField;
            }
            set
            {
                this.dbTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Parameter
    {
        
        private string nameField;
        
        private string parameter1Field;
        
        private string typeField;
        
        private string dbTypeField;
        
        private ParameterDirection directionField;
        
        private bool directionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Parameter")]
        public string Parameter1
        {
            get
            {
                return this.parameter1Field;
            }
            set
            {
                this.parameter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DbType
        {
            get
            {
                return this.dbTypeField;
            }
            set
            {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ParameterDirection Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectionSpecified
        {
            get
            {
                return this.directionFieldSpecified;
            }
            set
            {
                this.directionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum ParameterDirection
    {
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Out,
        
        /// <remarks/>
        InOut,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Function
    {
        
        private System.Collections.Generic.List<Parameter> parameterField;
        
        private System.Collections.Generic.List<object> itemsField;
        
        private string nameField;
        
        private string idField;
        
        private string methodField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private MemberModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        private bool hasMultipleResultsField;
        
        private bool hasMultipleResultsFieldSpecified;
        
        private bool isComposableField;
        
        private bool isComposableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter", Order=0)]
        public System.Collections.Generic.List<Parameter> Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementType", typeof(Type), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Return", typeof(Return), Order=1)]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MemberModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HasMultipleResults
        {
            get
            {
                return this.hasMultipleResultsField;
            }
            set
            {
                this.hasMultipleResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasMultipleResultsSpecified
        {
            get
            {
                return this.hasMultipleResultsFieldSpecified;
            }
            set
            {
                this.hasMultipleResultsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsComposable
        {
            get
            {
                return this.isComposableField;
            }
            set
            {
                this.isComposableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsComposableSpecified
        {
            get
            {
                return this.isComposableFieldSpecified;
            }
            set
            {
                this.isComposableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Type
    {
        
        private System.Collections.Generic.List<object> itemsField;
        
        private System.Collections.Generic.List<Type> type1Field;
        
        private string idRefField;
        
        private string idField;
        
        private string nameField;
        
        private string inheritanceCodeField;
        
        private bool isInheritanceDefaultField;
        
        private bool isInheritanceDefaultFieldSpecified;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private ClassModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association", typeof(Association), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Column", typeof(Column), Order=0)]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type", Order=1)]
        public System.Collections.Generic.List<Type> Type1
        {
            get
            {
                return this.type1Field;
            }
            set
            {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string IdRef
        {
            get
            {
                return this.idRefField;
            }
            set
            {
                this.idRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InheritanceCode
        {
            get
            {
                return this.inheritanceCodeField;
            }
            set
            {
                this.inheritanceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsInheritanceDefault
        {
            get
            {
                return this.isInheritanceDefaultField;
            }
            set
            {
                this.isInheritanceDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsInheritanceDefaultSpecified
        {
            get
            {
                return this.isInheritanceDefaultFieldSpecified;
            }
            set
            {
                this.isInheritanceDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ClassModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Association
    {
        
        private string nameField;
        
        private string memberField;
        
        private string storageField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private MemberModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        private string typeField;
        
        private string thisKeyField;
        
        private string otherKeyField;
        
        private bool isForeignKeyField;
        
        private bool isForeignKeyFieldSpecified;
        
        private Cardinality cardinalityField;
        
        private bool cardinalityFieldSpecified;
        
        private string deleteRuleField;
        
        private bool deleteOnNullField;
        
        private bool deleteOnNullFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Storage
        {
            get
            {
                return this.storageField;
            }
            set
            {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MemberModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ThisKey
        {
            get
            {
                return this.thisKeyField;
            }
            set
            {
                this.thisKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherKey
        {
            get
            {
                return this.otherKeyField;
            }
            set
            {
                this.otherKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsForeignKey
        {
            get
            {
                return this.isForeignKeyField;
            }
            set
            {
                this.isForeignKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsForeignKeySpecified
        {
            get
            {
                return this.isForeignKeyFieldSpecified;
            }
            set
            {
                this.isForeignKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Cardinality Cardinality
        {
            get
            {
                return this.cardinalityField;
            }
            set
            {
                this.cardinalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardinalitySpecified
        {
            get
            {
                return this.cardinalityFieldSpecified;
            }
            set
            {
                this.cardinalityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeleteRule
        {
            get
            {
                return this.deleteRuleField;
            }
            set
            {
                this.deleteRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DeleteOnNull
        {
            get
            {
                return this.deleteOnNullField;
            }
            set
            {
                this.deleteOnNullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteOnNullSpecified
        {
            get
            {
                return this.deleteOnNullFieldSpecified;
            }
            set
            {
                this.deleteOnNullFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum AccessModifier
    {
        
        /// <remarks/>
        Public,
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Protected,
        
        /// <remarks/>
        ProtectedInternal,
        
        /// <remarks/>
        Private,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum MemberModifier
    {
        
        /// <remarks/>
        Virtual,
        
        /// <remarks/>
        Override,
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        NewVirtual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum Cardinality
    {
        
        /// <remarks/>
        One,
        
        /// <remarks/>
        Many,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Column
    {
        
        private string nameField;
        
        private string memberField;
        
        private string storageField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private MemberModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        private string typeField;
        
        private string dbTypeField;
        
        private bool isReadOnlyField;
        
        private bool isReadOnlyFieldSpecified;
        
        private bool isPrimaryKeyField;
        
        private bool isPrimaryKeyFieldSpecified;
        
        private bool isDbGeneratedField;
        
        private bool isDbGeneratedFieldSpecified;
        
        private bool canBeNullField;
        
        private bool canBeNullFieldSpecified;
        
        private UpdateCheck updateCheckField;
        
        private bool updateCheckFieldSpecified;
        
        private bool isDiscriminatorField;
        
        private bool isDiscriminatorFieldSpecified;
        
        private string expressionField;
        
        private bool isVersionField;
        
        private bool isVersionFieldSpecified;
        
        private bool isDelayLoadedField;
        
        private bool isDelayLoadedFieldSpecified;
        
        private AutoSync autoSyncField;
        
        private bool autoSyncFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Storage
        {
            get
            {
                return this.storageField;
            }
            set
            {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MemberModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DbType
        {
            get
            {
                return this.dbTypeField;
            }
            set
            {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsReadOnly
        {
            get
            {
                return this.isReadOnlyField;
            }
            set
            {
                this.isReadOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsReadOnlySpecified
        {
            get
            {
                return this.isReadOnlyFieldSpecified;
            }
            set
            {
                this.isReadOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPrimaryKey
        {
            get
            {
                return this.isPrimaryKeyField;
            }
            set
            {
                this.isPrimaryKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPrimaryKeySpecified
        {
            get
            {
                return this.isPrimaryKeyFieldSpecified;
            }
            set
            {
                this.isPrimaryKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsDbGenerated
        {
            get
            {
                return this.isDbGeneratedField;
            }
            set
            {
                this.isDbGeneratedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDbGeneratedSpecified
        {
            get
            {
                return this.isDbGeneratedFieldSpecified;
            }
            set
            {
                this.isDbGeneratedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CanBeNull
        {
            get
            {
                return this.canBeNullField;
            }
            set
            {
                this.canBeNullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanBeNullSpecified
        {
            get
            {
                return this.canBeNullFieldSpecified;
            }
            set
            {
                this.canBeNullFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UpdateCheck UpdateCheck
        {
            get
            {
                return this.updateCheckField;
            }
            set
            {
                this.updateCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateCheckSpecified
        {
            get
            {
                return this.updateCheckFieldSpecified;
            }
            set
            {
                this.updateCheckFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsDiscriminator
        {
            get
            {
                return this.isDiscriminatorField;
            }
            set
            {
                this.isDiscriminatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDiscriminatorSpecified
        {
            get
            {
                return this.isDiscriminatorFieldSpecified;
            }
            set
            {
                this.isDiscriminatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsVersion
        {
            get
            {
                return this.isVersionField;
            }
            set
            {
                this.isVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsVersionSpecified
        {
            get
            {
                return this.isVersionFieldSpecified;
            }
            set
            {
                this.isVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsDelayLoaded
        {
            get
            {
                return this.isDelayLoadedField;
            }
            set
            {
                this.isDelayLoadedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDelayLoadedSpecified
        {
            get
            {
                return this.isDelayLoadedFieldSpecified;
            }
            set
            {
                this.isDelayLoadedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AutoSync AutoSync
        {
            get
            {
                return this.autoSyncField;
            }
            set
            {
                this.autoSyncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoSyncSpecified
        {
            get
            {
                return this.autoSyncFieldSpecified;
            }
            set
            {
                this.autoSyncFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum UpdateCheck
    {
        
        /// <remarks/>
        Always,
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        WhenChanged,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum AutoSync
    {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        OnInsert,
        
        /// <remarks/>
        OnUpdate,
        
        /// <remarks/>
        Always,
        
        /// <remarks/>
        Default,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum ClassModifier
    {
        
        /// <remarks/>
        Sealed,
        
        /// <remarks/>
        Abstract,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class TableFunctionReturn
    {
        
        private string memberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class TableFunctionParameter
    {
        
        private string parameterField;
        
        private string memberField;
        
        private Version versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Version Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum Version
    {
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Original,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class TableFunction
    {
        
        private System.Collections.Generic.List<TableFunctionParameter> argumentField;
        
        private TableFunctionReturn returnField;
        
        private string functionIdField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Argument", Order=0)]
        public System.Collections.Generic.List<TableFunctionParameter> Argument
        {
            get
            {
                return this.argumentField;
            }
            set
            {
                this.argumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TableFunctionReturn Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string FunctionId
        {
            get
            {
                return this.functionIdField;
            }
            set
            {
                this.functionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=true)]
    public partial class Table
    {
        
        private Type typeField;
        
        private TableFunction insertFunctionField;
        
        private TableFunction updateFunctionField;
        
        private TableFunction deleteFunctionField;
        
        private string nameField;
        
        private string memberField;
        
        private AccessModifier accessModifierField;
        
        private bool accessModifierFieldSpecified;
        
        private MemberModifier modifierField;
        
        private bool modifierFieldSpecified;
        
        /// <remarks/>
        public Type Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public TableFunction InsertFunction
        {
            get
            {
                return this.insertFunctionField;
            }
            set
            {
                this.insertFunctionField = value;
            }
        }
        
        /// <remarks/>
        public TableFunction UpdateFunction
        {
            get
            {
                return this.updateFunctionField;
            }
            set
            {
                this.updateFunctionField = value;
            }
        }
        
        /// <remarks/>
        public TableFunction DeleteFunction
        {
            get
            {
                return this.deleteFunctionField;
            }
            set
            {
                this.deleteFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccessModifier AccessModifier
        {
            get
            {
                return this.accessModifierField;
            }
            set
            {
                this.accessModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModifierSpecified
        {
            get
            {
                return this.accessModifierFieldSpecified;
            }
            set
            {
                this.accessModifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MemberModifier Modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return this.modifierFieldSpecified;
            }
            set
            {
                this.modifierFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/linqtosql/dbml/2007", IsNullable=false)]
    public enum SerializationMode
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Unidirectional,
    }
    
    /// <summary>
    /// Factory class for classes defined in the DbmlSchema schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.4.0")]
    public sealed partial class DbmlSchemaFactory
    {
        
        private static string[] _schemas = new string[] {
                "<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<xs:schema xmlns:xs=\"http://www.w3.org/2" +
                    "001/XMLSchema\" targetNamespace=\"http://schemas.microsoft.com/linqtosql/dbml/2007" +
                    "\" xmlns=\"http://schemas.microsoft.com/linqtosql/dbml/2007\"\r\nelementFormDefault=\"" +
                    "qualified\" >\r\n  <xs:element name=\"Database\" type=\"Database\" />\r\n  <xs:complexTyp" +
                    "e name=\"Database\">\r\n    <xs:sequence>\r\n      <xs:element name=\"Connection\" type=" +
                    "\"Connection\" minOccurs=\"0\" maxOccurs=\"1\" />\r\n      <xs:element name=\"Table\" type" +
                    "=\"Table\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\r\n      <xs:element name=\"Functio" +
                    "n\" type=\"Function\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\r\n    </xs:sequence>\r\n " +
                    "   <xs:attribute name=\"Name\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribu" +
                    "te name=\"EntityNamespace\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute " +
                    "name=\"ContextNamespace\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute na" +
                    "me=\"Class\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"AccessMod" +
                    "ifier\" type=\"AccessModifier\" use=\"optional\" />\r\n    <xs:attribute name=\"Modifier" +
                    "\" type=\"ClassModifier\" use=\"optional\" />\r\n    <xs:attribute name=\"BaseType\" type" +
                    "=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Provider\" type=\"xs:strin" +
                    "g\" use=\"optional\" />\r\n    <xs:attribute name=\"ExternalMapping\" type=\"xs:boolean\"" +
                    " use=\"optional\" />\r\n    <xs:attribute name=\"Serialization\" type=\"SerializationMo" +
                    "de\" use=\"optional\" />\r\n    <xs:attribute name=\"EntityBase\" type=\"xs:string\" use=" +
                    "\"optional\" />\r\n  </xs:complexType>\r\n  <xs:complexType name=\"Table\">\r\n    <xs:all" +
                    ">\r\n      <xs:element name=\"Type\" type=\"Type\" minOccurs=\"1\" maxOccurs=\"1\" />\r\n   " +
                    "   <xs:element name=\"InsertFunction\" type=\"TableFunction\" minOccurs=\"0\" maxOccur" +
                    "s=\"1\" />\r\n      <xs:element name=\"UpdateFunction\" type=\"TableFunction\" minOccurs" +
                    "=\"0\" maxOccurs=\"1\" />\r\n      <xs:element name=\"DeleteFunction\" type=\"TableFuncti" +
                    "on\" minOccurs=\"0\" maxOccurs=\"1\" />\r\n    </xs:all>\r\n    <xs:attribute name=\"Name\"" +
                    " type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute name=\"Member\" type=\"xs:st" +
                    "ring\" use=\"optional\" />\r\n    <xs:attribute name=\"AccessModifier\" type=\"AccessMod" +
                    "ifier\" use=\"optional\" />\r\n    <xs:attribute name=\"Modifier\" type=\"MemberModifier" +
                    "\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:complexType name=\"Type\">\r\n    <x" +
                    "s:sequence>\r\n      <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\r\n        <xs:" +
                    "element name=\"Column\" type=\"Column\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\r\n    " +
                    "    <xs:element name=\"Association\" type=\"Association\" minOccurs=\"0\" maxOccurs=\"u" +
                    "nbounded\" />\r\n      </xs:choice>\r\n      <xs:element name=\"Type\" type=\"Type\" minO" +
                    "ccurs=\"0\" maxOccurs=\"unbounded\" />\r\n    </xs:sequence>\r\n    <xs:attribute name=\"" +
                    "IdRef\" type=\"xs:IDREF\" use=\"optional\" />\r\n    <xs:attribute name=\"Id\" type=\"xs:I" +
                    "D\" use=\"optional\" />\r\n    <xs:attribute name=\"Name\" type=\"xs:string\" use=\"option" +
                    "al\" />\r\n    <xs:attribute name=\"InheritanceCode\" type=\"xs:string\" use=\"optional\"" +
                    " />\r\n    <xs:attribute name=\"IsInheritanceDefault\" type=\"xs:boolean\" use=\"option" +
                    "al\" />\r\n    <xs:attribute name=\"AccessModifier\" type=\"AccessModifier\" use=\"optio" +
                    "nal\" />\r\n    <xs:attribute name=\"Modifier\" type=\"ClassModifier\" use=\"optional\" /" +
                    ">\r\n  </xs:complexType>\r\n  <xs:complexType name=\"Column\">\r\n    <xs:attribute name" +
                    "=\"Name\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Member\" type" +
                    "=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Storage\" type=\"xs:string" +
                    "\" use=\"optional\" />\r\n    <xs:attribute name=\"AccessModifier\" type=\"AccessModifie" +
                    "r\" use=\"optional\" />\r\n    <xs:attribute name=\"Modifier\" type=\"MemberModifier\" us" +
                    "e=\"optional\" />\r\n    <xs:attribute name=\"Type\" type=\"xs:string\" use=\"required\" /" +
                    ">\r\n    <xs:attribute name=\"DbType\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:a" +
                    "ttribute name=\"IsReadOnly\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attribut" +
                    "e name=\"IsPrimaryKey\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attribute nam" +
                    "e=\"IsDbGenerated\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attribute name=\"C" +
                    "anBeNull\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attribute name=\"UpdateChe" +
                    "ck\" type=\"UpdateCheck\" use=\"optional\" />\r\n    <xs:attribute name=\"IsDiscriminato" +
                    "r\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attribute name=\"Expression\" type" +
                    "=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"IsVersion\" type=\"xs:bool" +
                    "ean\" use=\"optional\" />\r\n    <xs:attribute name=\"IsDelayLoaded\" type=\"xs:boolean\"" +
                    " use=\"optional\" />\r\n    <xs:attribute name=\"AutoSync\" type=\"AutoSync\" use=\"optio" +
                    "nal\" />\r\n  </xs:complexType>\r\n  <xs:complexType name=\"Association\">\r\n    <xs:att" +
                    "ribute name=\"Name\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute name=\"M" +
                    "ember\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute name=\"Storage\" type" +
                    "=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"AccessModifier\" type=\"Ac" +
                    "cessModifier\" use=\"optional\" />\r\n    <xs:attribute name=\"Modifier\" type=\"MemberM" +
                    "odifier\" use=\"optional\" />\r\n    <xs:attribute name=\"Type\" type=\"xs:string\" use=\"" +
                    "required\" />\r\n    <xs:attribute name=\"ThisKey\" type=\"xs:string\" use=\"optional\" /" +
                    ">\r\n    <xs:attribute name=\"OtherKey\" type=\"xs:string\" use=\"optional\" />\r\n    <xs" +
                    ":attribute name=\"IsForeignKey\" type=\"xs:boolean\" use=\"optional\" />\r\n    <xs:attr" +
                    "ibute name=\"Cardinality\" type=\"Cardinality\" use=\"optional\" />\r\n    <xs:attribute" +
                    " name=\"DeleteRule\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"D" +
                    "eleteOnNull\" type=\"xs:boolean\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:com" +
                    "plexType name=\"Function\">\r\n    <xs:sequence>\r\n      <xs:element name=\"Parameter\"" +
                    " type=\"Parameter\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\r\n      <xs:choice>\r\n   " +
                    "     <xs:element name=\"ElementType\" type=\"Type\" minOccurs=\"0\" maxOccurs=\"unbound" +
                    "ed\" />\r\n        <xs:element name=\"Return\" type=\"Return\" minOccurs=\"0\" maxOccurs=" +
                    "\"1\" />\r\n      </xs:choice>\r\n    </xs:sequence>\r\n    <xs:attribute name=\"Name\" ty" +
                    "pe=\"xs:string\" use=\"required\" />\r\n    <xs:attribute name=\"Id\" type=\"xs:ID\" use=\"" +
                    "optional\" />\r\n    <xs:attribute name=\"Method\" type=\"xs:string\" use=\"optional\" />" +
                    "\r\n    <xs:attribute name=\"AccessModifier\" type=\"AccessModifier\" use=\"optional\" /" +
                    ">\r\n    <xs:attribute name=\"Modifier\" type=\"MemberModifier\" use=\"optional\" />\r\n  " +
                    "  <xs:attribute name=\"HasMultipleResults\" type=\"xs:boolean\" use=\"optional\" />\r\n " +
                    "   <xs:attribute name=\"IsComposable\" type=\"xs:boolean\" use=\"optional\" />\r\n  </xs" +
                    ":complexType>\r\n  <xs:complexType name=\"TableFunction\">\r\n    <xs:sequence>\r\n     " +
                    " <xs:element name=\"Argument\" type=\"TableFunctionParameter\" minOccurs=\"0\" maxOccu" +
                    "rs=\"unbounded\" />\r\n      <xs:element name=\"Return\" type=\"TableFunctionReturn\" mi" +
                    "nOccurs=\"0\" maxOccurs=\"1\" />\r\n    </xs:sequence>\r\n    <xs:attribute name=\"Functi" +
                    "onId\" type=\"xs:IDREF\" use=\"required\" />\r\n    <xs:attribute name=\"AccessModifier\"" +
                    " type=\"AccessModifier\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:complexType" +
                    " name=\"Parameter\">\r\n    <xs:attribute name=\"Name\" type=\"xs:string\" use=\"required" +
                    "\" />\r\n    <xs:attribute name=\"Parameter\" type=\"xs:string\" use=\"optional\" />\r\n   " +
                    " <xs:attribute name=\"Type\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute" +
                    " name=\"DbType\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Direc" +
                    "tion\" type=\"ParameterDirection\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:co" +
                    "mplexType name=\"Return\">\r\n    <xs:attribute name=\"Type\" type=\"xs:string\" use=\"re" +
                    "quired\" />\r\n    <xs:attribute name=\"DbType\" type=\"xs:string\" use=\"optional\" />\r\n" +
                    "  </xs:complexType>\r\n  <xs:complexType name=\"TableFunctionParameter\">\r\n    <xs:a" +
                    "ttribute name=\"Parameter\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute " +
                    "name=\"Member\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute name=\"Versio" +
                    "n\" type=\"Version\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:complexType name" +
                    "=\"TableFunctionReturn\">\r\n    <xs:attribute name=\"Member\" type=\"xs:string\" use=\"r" +
                    "equired\" />\r\n  </xs:complexType>\r\n  <xs:complexType name=\"Connection\">\r\n    <xs:" +
                    "attribute name=\"Provider\" type=\"xs:string\" use=\"required\" />\r\n    <xs:attribute " +
                    "name=\"Mode\" type=\"ConnectionMode\" use=\"optional\" />\r\n    <xs:attribute name=\"Con" +
                    "nectionString\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Setti" +
                    "ngsObjectName\" type=\"xs:string\" use=\"optional\" />\r\n    <xs:attribute name=\"Setti" +
                    "ngsPropertyName\" type=\"xs:string\" use=\"optional\" />\r\n  </xs:complexType>\r\n  <xs:" +
                    "simpleType name=\"ConnectionMode\">\r\n    <xs:restriction base=\"xs:string\">\r\n      " +
                    "<xs:enumeration value=\"ConnectionString\" />\r\n      <xs:enumeration value=\"AppSet" +
                    "tings\" />\r\n      <xs:enumeration value=\"WebSettings\" />\r\n    </xs:restriction>\r\n" +
                    "  </xs:simpleType>\r\n  <xs:simpleType name=\"AccessModifier\">\r\n    <xs:restriction" +
                    " base=\"xs:string\">\r\n      <xs:enumeration value=\"Public\" />\r\n      <xs:enumerati" +
                    "on value=\"Internal\" />\r\n      <xs:enumeration value=\"Protected\" />\r\n      <xs:en" +
                    "umeration value=\"ProtectedInternal\" />\r\n      <xs:enumeration value=\"Private\" />" +
                    "\r\n    </xs:restriction>\r\n  </xs:simpleType>\r\n  <xs:simpleType name=\"UpdateCheck\"" +
                    ">\r\n    <xs:restriction base=\"xs:string\">\r\n      <xs:enumeration value=\"Always\" /" +
                    ">\r\n      <xs:enumeration value=\"Never\" />\r\n      <xs:enumeration value=\"WhenChan" +
                    "ged\" />\r\n    </xs:restriction>\r\n  </xs:simpleType>\r\n  <xs:simpleType name=\"Seria" +
                    "lizationMode\">\r\n    <xs:restriction base=\"xs:string\">\r\n      <xs:enumeration val" +
                    "ue=\"None\" />\r\n      <xs:enumeration value=\"Unidirectional\" />\r\n    </xs:restrict" +
                    "ion>\r\n  </xs:simpleType>\r\n  <xs:simpleType name=\"ParameterDirection\">\r\n    <xs:r" +
                    "estriction base=\"xs:string\">\r\n      <xs:enumeration value=\"In\" />\r\n      <xs:enu" +
                    "meration value=\"Out\" />\r\n      <xs:enumeration value=\"InOut\" />\r\n    </xs:restri" +
                    "ction>\r\n  </xs:simpleType>\r\n  <xs:simpleType name=\"Version\">\r\n    <xs:restrictio" +
                    "n base=\"xs:string\">\r\n      <xs:enumeration value=\"Current\" />\r\n      <xs:enumera" +
                    "tion value=\"Original\" />\r\n    </xs:restriction>\r\n  </xs:simpleType>\r\n  <xs:simpl" +
                    "eType name=\"AutoSync\">\r\n    <xs:restriction base=\"xs:string\">\r\n      <xs:enumera" +
                    "tion value=\"Never\" />\r\n      <xs:enumeration value=\"OnInsert\" />\r\n      <xs:enum" +
                    "eration value=\"OnUpdate\" />\r\n      <xs:enumeration value=\"Always\" />\r\n      <xs:" +
                    "enumeration value=\"Default\" />\r\n    </xs:restriction>\r\n  </xs:simpleType>\r\n  <xs" +
                    ":simpleType name=\"ClassModifier\">\r\n    <xs:restriction base=\"xs:string\">\r\n      " +
                    "<xs:enumeration value=\"Sealed\" />\r\n      <xs:enumeration value=\"Abstract\" />\r\n  " +
                    "  </xs:restriction>\r\n  </xs:simpleType>\r\n  <xs:simpleType name=\"MemberModifier\">" +
                    "\r\n    <xs:restriction base=\"xs:string\">\r\n      <xs:enumeration value=\"Virtual\" /" +
                    ">\r\n      <xs:enumeration value=\"Override\" />\r\n      <xs:enumeration value=\"New\" " +
                    "/>\r\n      <xs:enumeration value=\"NewVirtual\" />\r\n    </xs:restriction>\r\n  </xs:s" +
                    "impleType>\r\n  <xs:simpleType name=\"Cardinality\">\r\n    <xs:restriction base=\"xs:s" +
                    "tring\">\r\n      <xs:enumeration value=\"One\" />\r\n      <xs:enumeration value=\"Many" +
                    "\" />\r\n    </xs:restriction>\r\n  </xs:simpleType>\r\n</xs:schema>\r\n"};
        
        private static System.Xml.Schema.XmlSchemaSet _xmlSchemaSet;
        
        private System.Text.StringBuilder _sb;
        
        static DbmlSchemaFactory()
        {
            _xmlSchemaSet = new System.Xml.Schema.XmlSchemaSet();
            for (int i = 0; (i < _schemas.Length); i = (i + 1))
            {
                _xmlSchemaSet.Add(System.Xml.Schema.XmlSchema.Read(new System.IO.StringReader(_schemas[i]), null));
            }
            _xmlSchemaSet.Compile();
        }
        
        /// <summary>
        /// The contents of the DbmlSchema schema and the imported schema.
        /// It is used to check the validity of XML files against the XML schema.
        /// </summary>
        public static string[] Schemas
        {
            get
            {
                return _schemas;
            }
        }
        
        /// <summary>
        /// Gets a compiled schema set containing the DbmlSchema schema and all included schemas.
        /// </summary>
        public static System.Xml.Schema.XmlSchemaSet XmlSchemaSet
        {
            get
            {
                return _xmlSchemaSet;
            }
        }
        
        private void ValidationCallBack(object sender, System.Xml.Schema.ValidationEventArgs e)
        {
            if ((this._sb.Length > 0))
            {
                this._sb.AppendLine();
            }
            this._sb.AppendFormat("Xml Validation Error ({0}, {1}): {2}", e.Exception.LineNumber, e.Exception.LinePosition, e.Message);
        }
        
        private T DoCreate<T>(System.Xml.XmlReader xmlReader)
        
        {
            if ((xmlReader == null))
            {
                throw new System.ArgumentNullException("xmlReader");
            }
            this._sb = new System.Text.StringBuilder();
            System.Xml.XmlReaderSettings xmlReaderSettings = new System.Xml.XmlReaderSettings();
            xmlReaderSettings.ValidationType = System.Xml.ValidationType.Schema;
            xmlReaderSettings.Schemas = XmlSchemaSet;
            xmlReaderSettings.ValidationEventHandler += new System.Xml.Schema.ValidationEventHandler(this.ValidationCallBack);
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
            T result;
            System.Xml.XmlReader validatingXmlReader = System.Xml.XmlReader.Create(xmlReader, xmlReaderSettings);
            try
            {
                result = ((T)(xmlSerializer.Deserialize(validatingXmlReader)));
            }
            finally
            {
                ((System.IDisposable)(validatingXmlReader)).Dispose();
            }
            string errors = this._sb.ToString();
            if ((errors.Length > 0))
            {
                throw new System.Xml.XmlException(errors);
            }
            return result;
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="xmlReader"/>.</typeparam>
        /// <param name="xmlReader">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.Xml.XmlReader xmlReader)
        
        {
            return new DbmlSchemaFactory().DoCreate<T>(xmlReader);
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="stream"/>.</typeparam>
        /// <param name="stream">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.IO.Stream stream)
        
        {
            if ((stream == null))
            {
                throw new System.ArgumentNullException("stream");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(stream);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="path"/>.</typeparam>
        /// <param name="path">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(string path)
        
        {
            if (string.IsNullOrEmpty(path))
            {
                throw new System.ArgumentNullException("path");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(path);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="textReader"/>.</typeparam>
        /// <param name="textReader">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.IO.TextReader textReader)
        
        {
            if ((textReader == null))
            {
                throw new System.ArgumentNullException("textReader");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(textReader);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="projectItem"/>.</typeparam>
        /// <param name="projectItem">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(Kodeo.Reegenerator.Wrappers.ProjectItem projectItem)
        
        {
            if ((projectItem == null))
            {
                throw new System.ArgumentNullException("projectItem");
            }
            T result = Create<T>(projectItem.FullPath);
            if (typeof(Kodeo.Reegenerator.Generators.Xsd.IInitializable).IsAssignableFrom(typeof(T)))
            {
                ((Kodeo.Reegenerator.Generators.Xsd.IInitializable)(result)).Init(projectItem);
            }
            return result;
        }
    }
}
