// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator
// Generator: RgenTemplate (internal)
// Generation date: 2013-12-22 11:23
// Generated by: KODEOACER\radusib
// -------------------------------------------------------
namespace CustomizeDesigners.Resources
{
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.4.0")]
    public partial class ResourcesRenderer : Kodeo.Reegenerator.Generators.CodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<returns></returns>
        public override Kodeo.Reegenerator.Generators.RenderResults Render()
        {
            base.Output.Write("// -------------------------------------------------------\r\n// Automatically gene" +
                    "rated with Kodeo\'s Reegenerator\r\n// Generator: CustomizeDesigners.Resources.Reso" +
                    "urcesRenderer\r\n// Generation date: ");
            base.Output.Write( System.DateTime.Now.ToString("yyyy-MM-dd hh:mm") );
            base.Output.Write("\r\n// Generated by: ");
            base.Output.Write( System.Security.Principal.WindowsIdentity.GetCurrent().Name );
            base.Output.Write("\r\n// -------------------------------------------------------\r\n\r\n\r\nnamespace ");
            base.Output.Write( base.ProjectItem.CodeNamespace );
            base.Output.Write(@" {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""2.0.0.0"")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(""Microsoft.Performance"", ""CA1811:AvoidUncalledPrivateCode"")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""");
            base.Output.Write( base.ProjectItem.Project.RootNamespace );
            base.Output.Write(@".Properties.Resources"", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
");
 RenderAll(); 
            base.Output.Write("\r\n\t}\r\n}");
            base.Output.WriteLine();
            return new Kodeo.Reegenerator.Generators.RenderResults(base.Output.ToString());
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="data"></param>
        public virtual void RenderString(rootData data)
        {
            base.Output.Write("\t\t/// <summary>\r\n\t\t///   Looks up a localized string similar to ");
            base.Output.Write( data.value );
            base.Output.Write(".\r\n\t\t/// </summary>\r\n\t\tinternal static string ");
            base.Output.Write( data.name );
            base.Output.Write(" {\r\n\t\t\tget {\r\n\t\t\t\treturn ResourceManager.GetString(\"");
            base.Output.Write( data.name );
            base.Output.Write("\", resourceCulture);\r\n\t\t\t}\r\n\t\t}\r\n");
            base.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="data"></param>
        ///<param name="type"></param>
        public virtual void RenderResource(rootData data, System.String type)
        {
            base.Output.Write("\t\tinternal static ");
            base.Output.Write( type );
            base.Output.Write(" ");
            base.Output.Write( data.name );
            base.Output.Write(" {\r\n\t\t\tget {\r\n\t\t\t\tobject obj = ResourceManager.GetObject(\"");
            base.Output.Write( data.name );
            base.Output.Write("\", resourceCulture);\r\n\t\t\t\treturn ((");
            base.Output.Write( type );
            base.Output.Write(")(obj));\r\n\t\t\t}\r\n\t\t}");
            base.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="data"></param>
        ///<param name="content"></param>
        public virtual void RenderTextFileResource(rootData data, System.String content)
        {
            base.Output.Write("\t\t/// <summary>\r\n\t\t///   Looks up a localized string similar to ");
            base.Output.Write( DecorateMultiLine("\t///{0}", content) );
            base.Output.Write(".\r\n\t\t/// </summary>\r\n\t\tinternal static string ");
            base.Output.Write( data.name );
            base.Output.Write(" {\r\n\t\t\tget {\r\n\t\t\t\treturn ResourceManager.GetString(\"");
            base.Output.Write( data.name );
            base.Output.Write("\", resourceCulture);\r\n\t\t\t}\r\n\t\t}\r\n");
            base.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="data"></param>
        public virtual void RenderBinaryFileResource(rootData data)
        {
            base.Output.Write("\t\tinternal static System.IO.UnmanagedMemoryStream ");
            base.Output.Write( data.name );
            base.Output.Write(" {\r\n\t\t\tget {\r\n\t\t\t\treturn ResourceManager.GetStream(\"");
            base.Output.Write( data.name );
            base.Output.Write("\", resourceCulture);\r\n\t\t\t}\r\n\t\t}\r\n");
            base.Output.WriteLine();
        }
    }
}
